VNG-Realisatie/vng-api-common

- zds_schema/constants.py
Archiefnominatie and Archiefstatus
> Added enumerations for BrondatumArchiefprocedure_Afleidingswijze,

- zds_schema/constants.py
add `ZaakobjectTypes` and `BetalingsIndicatie` to **constants.py**
> add ZaakobjectTypes and BetalingsIndicatie to constants.py

- zds_schema/inspectors/geojson.py
**Issue**: https://github.com/VNG-Realisatie/gemma-zaken-common/issues/5
**Changes:**
1. Add condition for method = 'DELETE' in `GeometryFieldInspector` inspector
> add condition for delete method

- vng_api_common/middleware.py
- vng_api_common/permissions.py
**Changes:**
1. Add `client_id` key to `JWTPayload.payload`
1. Add new permission `ClientIdRequired` based on client_id
> add client_id to jwt_payload + new permission

- vng_api_common/notifications/kanalen.py
Issue - https://github.com/VNG-Realisatie/vng-api-common/issues/14 
**Changes:**
1. modify `kanaal.get_kenmerken` method
> Fixes #14 -- flatten get_kenmerken

- .bumpversion.cfg
- .gitignore
- bin/generate_notifications_api_spec.sh
- bin/patch_content_types
- manage.py
- openapi.yaml
- package-lock.json
- package.json
- swagger2.0.yaml
- testapp/schema.py
- testapp/settings.py
- testapp/urls.py
- testapp/views.py
- vng_api_common/inspectors/view.py
- vng_api_common/notifications/api/serializers.py
- vng_api_common/notifications/api/views.py
Fixes https://github.com/VNG-Realisatie/gemma-zaken/issues/806
* run `./bin/generate_notifications_api_spec.sh` to generate the spec
* the testapp is used to generate the spec
> Tooling to generate API spec for notifications receiving

- vng_api_common/middleware.py
- vng_api_common/permissions.py
- vng_api_common/tests/auth.py
**Changes:**
1. change permission class `AuthScopesRequired` - static fields to be checked are replaces with dynamic
1. change `JWTAuth.has_auth` - now it process dynamic number of fields
> replace static field names to dynamic in permission class

- vng_api_common/notifications/api/views.py
**Changes:**
1. Add new authorization format to `NotificationView`
> update permission classes and add action to notifications api

- vng_api_common/validators.py
This fixes the issue, but I'm not sure if this is the right way to fix it
> Issue #985: modified ResourceValidator to fix issue with URLValidator

- vng_api_common/validators.py
Step 1/2 in fixing https://github.com/VNG-Realisatie/gemma-zaken/issues/996
**Changes:**
1. add auth to ObjectInformatieObjectValidator
> add auth to ObjectInformatieObjectValidator

- vng_api_common/middleware.py
This payload will be used to retrieve user information for AuditTrails
> added function to retrieve payload to JWTAuth

- vng_api_common/utils.py
**Changes:**
1. add helper function `request_object_attribute`
> add function for unique representation of models

- vng_api_common/constants.py
- vng_api_common/inspectors/view.py
**Changes:**
1. Add NLX request headers to `AutoSchema`
> add nlx request headers to schema generation

- vng_api_common/audittrails/api/scopes.py
- vng_api_common/audittrails/viewsets.py
**Changes:**
1. Add scope and permissions to `AuditTrailViewSet`
> add auth to audittrails API

- vng_api_common/filters.py
needed for https://github.com/VNG-Realisatie/gemma-documentregistratiecomponent/pull/60
> Changes to support versioning for EnkelvoudigInformatieObject in drc

- vng_api_common/inspectors/polymorphic.py
- vng_api_common/polymorphism.py
Changes:
1. Add `group_field` to `Discriminator` and `PolymorphicSerializer`
> change polymorphism functional to support betrokkene data

- vng_api_common/inspectors/polymorphic.py
**Changes:**
1.  Convert discriminator field to camel case in polymorphic inspector
> convert discriminator to camel case

- vng_api_common/management/commands/generate_swagger.py
**Changes:**
1. Fix resource generation for schemes with lack of required fields
> resource generation for non-required fields

- vng_api_common/oas.py
Needed for resource validation in ZRC/DRC/BRC
> Temporary fix for certain edge cases for resource validation

- vng_api_common/management/commands/patch_error_contenttypes.py
Fixes Unicode code points `\xc3\xb6` vs `\xF6` UTF-8 literals. Only read/write UTF-8 literals.
> :checkered_flag: Fixes platform dependent encoding.

- vng_api_common/notifications/kanalen.py
- vng_api_common/notifications/tests/test_kanaal_documentation.py
- vng_api_common/notifications/utils.py
- vng_api_common/utils.py
needed for https://github.com/VNG-Realisatie/gemma-zaakregistratiecomponent/pull/109
> Added function to utils to generate notification documentation for OAS

- vng_api_common/schema.py
- vng_api_common/tests/schema.py
**Changes:**
1. Include `schema_path` to `SchemaView`
1. include `spec_url` to `get_operation_url`
> add parameter SPEC_URL to schema-related objects

- vng_api_common/management/commands/generate_swagger.py
**Changes:**
1. add `urlconf` and `info` parameters to `generate_swagger` command
> add parameters to generate_swagger command

- vng_api_common/notifications/utils.py
needed for https://github.com/VNG-Realisatie/gemma-zaaktypecatalogus/pull/60
> Removed Notifications header from documentation util

- vng_api_common/notifications/kanalen.py
- vng_api_common/notifications/viewsets.py
**Changes:**
1. Format kenmerken in `Kanaal` class based on serializer.data instead of model.field representation
> add data to get_kenmerken

- vng_api_common/inspectors/query.py
**Changes:**
1. Change `Parameter.description` for url filters which represent hyperlinked relations with inner resources
> change description for url fields to related resources

- vng_api_common/conf/api.py
for https://github.com/VNG-Realisatie/gemma-zaken/issues/1263
> Remove DRF default authentication classes

- vng_api_common/notifications/api/serializers.py
> :pencil: Updated notifications OAS docs.

- docs/conf.py
- testapp/settings.py
- vng_api_common/caching.py
- vng_api_common/conf/api.py
- vng_api_common/generators.py
- vng_api_common/inspectors/cache.py
- vng_api_common/inspectors/view.py
- vng_api_common/management/commands/generate_swagger.py
- vng_api_common/permissions.py
- vng_api_common/schema.py
- vng_api_common/search.py
- vng_api_common/tests/__init__.py
- vng_api_common/tests/caching.py
- vng_api_common/viewsets.py
> Implement calculating and outputting resource ETags

- vng_api_common/templates/vng_api_common/master.html
- vng_api_common/templatetags/vng_api_common.py
Issue - https://github.com/VNG-Realisatie/gemma-zaken/issues/1219
> add link to terms in the footnote if host is not local

- vng_api_common/geo.py
for https://github.com/VNG-Realisatie/gemma-zaken/issues/1279
> Stop checking for geo headers in case of destroy

- tests/test_autorisatie_validation.py
- vng_api_common/authorizations/validators.py
because otherwise creating an Autorisatie for ac/ztc/nrc causes an error
> Fixed issue with Autorisatie validator and components not in mapping

- setup.cfg
- testapp/settings.py
- tests/conftest.py
- tests/test_publish_validator.py
- vng_api_common/validators.py
Issue - https://github.com/VNG-Realisatie/gemma-zaken/issues/1337
> add PublishValidator to check concept field

- vng_api_common/viewsets.py
Issue - https://github.com/open-zaak/open-zaak/issues/141#issuecomment-548723349
> include condition if viewset has no filterset

- vng_api_common/authorizations/migrations/0011_auto_20191114_0728.py
- vng_api_common/constants.py
> Deprecated ObjectTypes in favor of custom made enums.

- vng_api_common/constants.py
for https://github.com/open-zaak/open-zaak/issues/205
> Fixed typo in brondatumArchiefprocedure.afleidingswijze Hoofzaak -> Hoofdzaak

- vng_api_common/notifications/handlers.py
fixes https://github.com/VNG-Realisatie/gemma-zaken/issues/1508
> Changed action from delete -> destroy in handler for authorization notifications

- vng_api_common/notifications/viewsets.py
issue https://github.com/open-zaak/open-zaak/issues/399
> Wrap notification actions in atomic transactions

- vng_api_common/middleware.py
Issue - https://github.com/open-zaak/open-zaak/issues/301
Related PR - https://github.com/open-zaak/open-zaak/pull/426
> exclude credentials without secrets from auth middleware

- vng_api_common/schema.py
related OZ issue: https://github.com/open-zaak/open-zaak/issues/495
related OZ PR: https://github.com/open-zaak/open-zaak/pull/525
> Allow setting of info parameter on SchemaView

- testapp/serializers.py
- tests/conftest.py
- tests/test_cache_headers.py
- tests/test_filters.py
- tests/test_nested_serializer_validation.py
- tests/test_schema_root_tags.py
- tests/test_utils.py
isort was returning errors.  This fixes them.
> Fix errors that isort returned

- vng_api_common/apps.py
- vng_api_common/inspectors/query.py
- vng_api_common/utils.py
for https://github.com/VNG-Realisatie/gemma-zaken/issues/1637
> Allow setting of min/max_length for query parameter inspector

- vng_api_common/validators.py
fix for: https://github.com/VNG-Realisatie/gemma-zaken/issues/1696
> :bug: Fix UniekeIdentificatieValidator for PATCH operations

- bin/generate_schema
- bin/generate_schema.cmd
- bin/use_external_components
- bin/use_external_components.cmd
- setup.cfg
- vng_api_common/conf/api.py
- vng_api_common/inspectors/view.py
- vng_api_common/management/commands/patch_error_contenttypes.py
- vng_api_common/management/commands/use_external_components.py
- vng_api_common/schema.py
- vng_api_common/schemas/common.yaml
- vng_api_common/views.py
Issue - https://github.com/VNG-Realisatie/gemma-zaken/issues/1582
> ref-responses

- docs/quickstart.rst
- vng_api_common/constants.py
* gemma-zaakregistratiecomponent -> zaken-api
* gemma-documentregistratiecomponent -> documenten-api
* gemma-zaaktypecatalogus -> catalogi-api
* gemma-besluitregistratiecomponent -> besluiten-api
* gemma-autorisatiecomponent -> autorisaties-api
> :memo: Rename components to fit common format

- vng_api_common/audittrails/viewsets.py
(cherry picked from commit 6ab9c0df3ac2ed829ea3967ad441e776fba4e700)
> :fire: Remove request_id from AuditTrail viewset/serializer

- .bumpversion.cfg
- package-lock.json
- package.json
- setup.cfg
because 1.0.55 on PyPI has migration conflicts
> :bookmark: Release version 1.0.56

- .bumpversion.cfg
- package-lock.json
- package.json
- setup.cfg
- vng_api_common/tests/auth.py
- vng_api_common/tests/compat.py
Required for: https://github.com/maykinmedia/objects-api/pull/222#discussion_r669522516
The packages `django-markup` and `markdown` are required to generate the notifications page, but were not included in `setup.cfg`
> :heavy_plus_sign: Add django-markup and markdown to requirements

- setup.cfg
- tests/test_jwt_decoding.py
- vng_api_common/conf/api.py
- vng_api_common/middleware.py
> Added JWT_LEEWAY setting to account for clock drift

- setup.cfg
- tests/test_check_query_params.py
- tests/test_register_webhook.py
- tests/test_utils.py
- vng_api_common/audittrails/viewsets.py
- vng_api_common/notifications/admin.py
- vng_api_common/utils.py
- vng_api_common/viewsets.py
Port changes made in stable/1.0.x to master
Required to get Open Zaak compatible with vng-api-common==1.6.4
> :sparkles: Port stable changes to master

- .bumpversion.cfg
- package-lock.json
- package.json
- setup.cfg
- tests/test_cache_headers.py
- vng_api_common/caching/registry.py
Now works for the following components:
> More fixes to caching decorator

- tests/test_cache_headers.py
- vng_api_common/caching/etags.py
> Fix cascading deletes if ETag re-calculations are involved

- vng_api_common/extensions/serializers/polymorphic.py
and make unique names for underlying map…
> add mapping to discriminator 
